//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.DeticRos
{
    [Serializable]
    public class SegmentationInfoMsg : Message
    {
        public const string k_RosMessageName = "detic_ros/SegmentationInfo";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public string[] detected_classes;
        public float[] scores;
        public Sensor.ImageMsg segmentation;

        public SegmentationInfoMsg()
        {
            this.header = new Std.HeaderMsg();
            this.detected_classes = new string[0];
            this.scores = new float[0];
            this.segmentation = new Sensor.ImageMsg();
        }

        public SegmentationInfoMsg(Std.HeaderMsg header, string[] detected_classes, float[] scores, Sensor.ImageMsg segmentation)
        {
            this.header = header;
            this.detected_classes = detected_classes;
            this.scores = scores;
            this.segmentation = segmentation;
        }

        public static SegmentationInfoMsg Deserialize(MessageDeserializer deserializer) => new SegmentationInfoMsg(deserializer);

        private SegmentationInfoMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.detected_classes, deserializer.ReadLength());
            deserializer.Read(out this.scores, sizeof(float), deserializer.ReadLength());
            this.segmentation = Sensor.ImageMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.detected_classes);
            serializer.Write(this.detected_classes);
            serializer.WriteLength(this.scores);
            serializer.Write(this.scores);
            serializer.Write(this.segmentation);
        }

        public override string ToString()
        {
            return "SegmentationInfoMsg: " +
            "\nheader: " + header.ToString() +
            "\ndetected_classes: " + System.String.Join(", ", detected_classes.ToList()) +
            "\nscores: " + System.String.Join(", ", scores.ToList()) +
            "\nsegmentation: " + segmentation.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
